cctutorial/cctutorial/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from cctutorial.views import home


urlpatterns = [
    re_path(r'^$', home, name='home'),
    path('admin/', admin.site.urls),
    path('polls/', include(('polls.urls', 'polls'), namespace='polls')),
]

cctutorial/polls/urls.py
from django.urls import path, re_path

from polls import views

urlpatterns = [
    path('', views.index, name='index'),
    path('most-popular/', views.most_popular_choice, name='most-popular-choice'),
    re_path(r'choices/(?P<pk>\d+)/', views.choices, name='choices'),
    path('choices/', views.choices, name='choices'),
    re_path('questions/(?P<pub_date>[0-9]{4}[-/][0-9]{2}[-/][0-9]{2})/', views.questions, name='questions'),
    re_path('questions/', views.questions, name='questions'),
]

cctutorial/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

cctutorial/cctutorial/views.py
from django.shortcuts import render


def home(request):
    rendered = render(request, 'polls/base.html', {})
    return rendered

cctutorial/polls/views.py
import datetime
from dateutil import parser
from django.shortcuts import render, get_object_or_404
from polls.models import Choice, Question


def index(request):
    latest_question_qs = Question.objects.only('pk',
                                               'pub_date',
                                               'question_text').order_by('-pub_date')[:5]
    rendered = render(request,
                      'polls/index.html',
                      {'questions': latest_question_qs,
                       'header': 'Latest Questions:'})
    return rendered


def most_popular_choice(request):
    """
    After you have created a series of questions and choices,
    return the choice with the most votes of all choices. If there
    are multiples with the same number of votes, return all. For
    the choice, display the choice_text, number of votes and
    related Question id in the response below.
    """
    questions = {}
    max_votes_qs = Choice.objects.order_by('-votes').values('votes')[:1]
    choices = Choice.objects.filter(votes=max_votes_qs).select_related('question')
    for choice in choices:
        questions.setdefault(choice.question, []).append(choice)

    rendered = render(request,
                      'polls/most-popular-choice.html',
                      {'questions': questions,
                       'header': 'Most Popular Choice(s):'})
    return rendered


def choices(request, pk=None):
    """
    If a primary key is passed in, return only that choice object.
    If no primary key is passed in, return all choices ordered by highest number of votes first.

    Show the related question in both instances
    """
    questions = set()

    if pk:
        choice = get_object_or_404(Choice, pk=pk)
        choices = [choice]
        header = f'Choice #{choice.pk}'
    else:
        choices = Choice.objects.all().order_by('pk').select_related('question')
        header = 'All Choices:'

    for choice in choices:
        questions.add(choice.question)

    rendered = render(request, 'polls/choices.html', {'questions': questions,
                                                      'choices': choices,
                                                      'header': header})
    return rendered


def _get_pub_date(pub_date):
    # I broke this out into a helper method to make testing a little easier
    if pub_date is None:
        pub_date = datetime.date.today()
    else:
        pub_date = parser.parse(pub_date).date()
    return pub_date


def questions(request, pub_date=None):
    pub_date = _get_pub_date(pub_date)

    # I'm a little confused about the goal for this method. I'm assuming we're
    # actually interested in the questions published either before or after some
    # date. I'm going to work under the assumption we want all questions created
    # before some date.
    questions = Question.objects.filter(pub_date__lte=pub_date)

    rendered = render(request,
                      'polls/questions.html',
                      {'questions': questions,
                       'header': f'Requested Pub Date: {pub_date.isoformat()}'})
    return rendered

cctutorial/polls/templates/polls/base.html
<html>
    <head>
        <title>CC Tutorial</title>
    </head>
    <body>
        <a href="{% url 'admin:index' %}">Admin</a>
        <a href="{% url 'polls:index' %}">Polls</a>
        <a href="{% url 'polls:questions' %}">Questions</a>
        <a href="{% url 'polls:choices' %}">Choices</a>
        <a href="{% url 'polls:most-popular-choice' %}">Most Popular Choice</a>

        {% if header %}
            <h2>
                {{ header }}
            </h2>
        {% endif %}

        {% block body %}
        {% endblock %}
    </body>
</html>

cctutorial/polls/templates/polls/choices.html
{% extends "polls/base.html" %}

{% block body %}
    {% if choices %}
        <h3>Choices</h3>
        <ul>
            {% for choice in choices %}
                <li>{{ choice }}</li>
            {% endfor %}
        </ul>

        <h3>Questions</h3>
        <ul>
            {% for question in questions %}
                <li>{{ question }}</li>
            {% endfor %}
        </ul>
    {% else %}
        No data to display
    {% endif %}
{% endblock %}

cctutorial/polls/templates/polls/index.html
{% extends "polls/base.html" %}

{% block body %}
    <ul>
        {% if questions %}
            {% for question in questions %}
                <li>
        Question: <a href="{% url 'admin:polls_question_change' question.pk %}">{{ question.pk }} - {{ question.question_text }}</a> Pub Date: {{ question.pub_date }}
                </li>
            {% endfor %}
        {% else %}
            No data to display
        {% endif %}
    </ul>
{% endblock %}

cctutorial/polls/templates/polls/most-popular-choice.html
{% extends "polls/base.html" %}

{% block body %}
    <ul>
        {% if questions %}
            {% for question, choices in questions.items %}
                <li>
                    Question: {{ question.pk }} - {{ question.question_text }}
                    <ul>
                        {% for choice in choices %}
                            <li>
                                Choice: {{ choice.pk }} - {{ choice.choice_text }} Votes: {{ choice.votes }}
                            </li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
        {% else %}
            No data to display
        {% endif %}
    </ul>
{% endblock %}

cctutorial/polls/templates/polls/questions.html
{% extends "polls/base.html" %}

{% block body %}
    <ul>
        {% if questions %}
            {% for question in questions %}
                <li>
                    Question: {{ question.pk }} - {{ question.question_text }} Pub Date: {{ question.pub_date }}
                </li>
            {% endfor %}
        {% else %}
            No data to display
        {% endif %}
    </ul>
{% endblock %}